replicaCount: 2

image:
  repository: 339712784473.dkr.ecr.us-east-1.amazonaws.com/daniel
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  hosts:
    - host: your-app.example.com
      paths:
        - "/"
  tls: []
