apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 339712784473.dkr.ecr.us-east-1.amazonaws.com/daniel
        #quark-frontend image v1
        resources:
          limits:
            memory: "256Mi"
            cpu: "0.125"
        ports:
        - containerPort: 80